name: Lint PR

on: [pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: '${{ github.head_ref }}'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run prettier
        run: yarn prettier

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Github Action"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes exist.";
            git add -A
            git commit -m "[CI] lint files"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" ${{ github.head_ref }}
          else
            echo "No change."
          fi
